# Object that should have namespace removed
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: default-profile
  namespace: kubeflow
spec:
  owner:
    kind: User
    name: alice@foo.com
