# coding: utf-8

"""
    Kubeflow Auth

    Access Management API.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: kubeflow-engineering@google.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Binding(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user': 'Subject',
        'referred_namespace': 'str',
        'role_ref': 'RoleRef',
        'status': 'str'
    }

    attribute_map = {
        'user': 'user',
        'referred_namespace': 'referredNamespace',
        'role_ref': 'RoleRef',
        'status': 'status'
    }

    def __init__(self, user=None, referred_namespace=None, role_ref=None, status=None):  # noqa: E501
        """Binding - a model defined in Swagger"""  # noqa: E501

        self._user = None
        self._referred_namespace = None
        self._role_ref = None
        self._status = None
        self.discriminator = None

        if user is not None:
            self.user = user
        if referred_namespace is not None:
            self.referred_namespace = referred_namespace
        if role_ref is not None:
            self.role_ref = role_ref
        if status is not None:
            self.status = status

    @property
    def user(self):
        """Gets the user of this Binding.  # noqa: E501


        :return: The user of this Binding.  # noqa: E501
        :rtype: Subject
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this Binding.


        :param user: The user of this Binding.  # noqa: E501
        :type: Subject
        """

        self._user = user

    @property
    def referred_namespace(self):
        """Gets the referred_namespace of this Binding.  # noqa: E501


        :return: The referred_namespace of this Binding.  # noqa: E501
        :rtype: str
        """
        return self._referred_namespace

    @referred_namespace.setter
    def referred_namespace(self, referred_namespace):
        """Sets the referred_namespace of this Binding.


        :param referred_namespace: The referred_namespace of this Binding.  # noqa: E501
        :type: str
        """

        self._referred_namespace = referred_namespace

    @property
    def role_ref(self):
        """Gets the role_ref of this Binding.  # noqa: E501


        :return: The role_ref of this Binding.  # noqa: E501
        :rtype: RoleRef
        """
        return self._role_ref

    @role_ref.setter
    def role_ref(self, role_ref):
        """Sets the role_ref of this Binding.


        :param role_ref: The role_ref of this Binding.  # noqa: E501
        :type: RoleRef
        """

        self._role_ref = role_ref

    @property
    def status(self):
        """Gets the status of this Binding.  # noqa: E501

        Status of the profile, one of Succeeded, Failed, Unknown.  # noqa: E501

        :return: The status of this Binding.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Binding.

        Status of the profile, one of Succeeded, Failed, Unknown.  # noqa: E501

        :param status: The status of this Binding.  # noqa: E501
        :type: str
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Binding, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Binding):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
